container:
  image: python:3

build_package_pippi_task:
  pip_cache:
    folder: ~/.cache/pip
    fingerprint_script: echo $PYTHON_VERSION
    populate_script: python3 -m pip install --upgrade setuptools wheel Cython==3.0.0a10 numpy
  build_package_pippi_script: make cirrus-install && python3 setup.py sdist bdist_wheel
